### ISSUE TITLE
Curl not working in phpfpm:7.4

### ISSUE THREAD

**Issue by Bleala** [adhocore/docker-phpfpm#40]
Hey there!

I am using your phpfpm:7.4 image and i noticed that "curl" is not working from inside the container.

Because some php code always failed i tested a simple command, "curl icanhazip.com", with which you get your external ip address.

This command is working from the host, it is working from inside an nginx container on that host, but not within your phpfpm:7.4 container which is also on that host.

Do i miss something, why curl is not working?

Greetings

**Comment by adhocore** [comment]
working, btw pls do `docker pull adhocore/phpfpm:7.4` first.
```sh
docker run --rm -it adhocore/phpfpm:7.4 curl icanhazip.com

182.***.***.*** 
```
(ip redacted)
