### ISSUE TITLE
Intl.so dependencies failure

### ISSUE THREAD

**Issue by fernando1419** [adhocore/docker-phpfpm#80]
Hi adhocore, I'm getting this error when php tries to load the intl extension when using your https://github.com/adhocore/docker-phpfpm/blob/main/8.1.Dockerfile . Do you happen to know how can I solve this out?.
Thanks in advance.

![image](https://user-images.githubusercontent.com/808696/224524152-84cd32f7-1e30-4be0-b19d-2d7f4c8e841e.png)

**Comment by fernando1419** [comment]
Thanks to you!, kind sir.
BTW, Yours is an excellent work!.

**Comment by adhocore** [comment]
will be resolved by [16ba827](https://github.com/adhocore/docker-phpfpm/commit/16ba827e280e8cc61b8829081257847a85a86911)
